import type { Action, ActionCategory } from "@/types"
import {
  BookOpen,
  CaseSensitive,
  ChevronRight,
  ClipboardCheck,
  FileText,
  Languages,
  List,
  ListOrdered,
  Maximize2,
  MessageCircleHeart,
  MessageCircleMore,
  Minimize2,
  NotebookPen,
  PartyPopper,
  PenLine,
  Scale,
  ScanText,
  Sparkles,
  RefreshCw,
  SpellCheck,
  SquarePen,
  StretchHorizontal,
  Target,
  TrendingUp,
  WandSparkles,
} from "lucide-react"

export const ACTION_CATEGORY_ORDER: ActionCategory[] = [
  "rewrite",
  "modify",
  "tone",
  "transform",
]

export const ACTION_CATEGORY_LABELS: Record<ActionCategory, string> = {
  rewrite: "Rewrite",
  modify: "Modify",
  tone: "Tone",
  transform: "Transform",
}

export const actions: Action[] = [
  {
    id: "improve-writing",
    label: "Improve writing",
    category: "rewrite",
    prompt: "Improve writing quality, clarity, and flow while preserving intent.",
    icon: TrendingUp,
  },
  {
    id: "fix-spelling-grammar",
    label: "Fix spelling and grammar",
    category: "rewrite",
    prompt: "Fix spelling, grammar, punctuation, and basic style while preserving meaning.",
    icon: SpellCheck,
  },
  {
    id: "rewrite-single-sentence",
    label: "Rewrite as a single sentence",
    category: "rewrite",
    prompt: "Rewrite the text as one clear, grammatically correct sentence.",
    icon: SquarePen,
  },
  {
    id: "convert-english-us",
    label: "Convert to English (US)",
    category: "rewrite",
    prompt: "Convert the text to natural, fluent American English.",
    icon: Languages,
  },
  {
    id: "simplify-language",
    label: "Simplify language",
    category: "rewrite",
    prompt: "Simplify wording and sentence structure for easier understanding.",
    icon: WandSparkles,
  },
  {
    id: "rewrite-single-paragraph",
    label: "Rewrite into a single paragraph",
    category: "rewrite",
    prompt: "Rewrite the text as one coherent paragraph.",
    icon: FileText,
  },
  {
    id: "continue-writing",
    label: "Continue writing",
    category: "rewrite",
    prompt: "Continue the text naturally in the same tone, style, and context.",
    icon: ChevronRight,
  },
  {
    id: "shorten-selection",
    label: "Shorten selection",
    category: "modify",
    prompt: "Make the text shorter while preserving the key meaning.",
    icon: Minimize2,
  },
  {
    id: "expand-selection",
    label: "Expand selection",
    category: "modify",
    prompt: "Expand the text with useful detail while preserving intent.",
    icon: Maximize2,
  },
  {
    id: "summarize-selection",
    label: "Summarize selection",
    category: "modify",
    prompt: "Summarize the text into concise key points.",
    icon: ScanText,
  },
  {
    id: "explain-selection",
    label: "Explain selection",
    category: "modify",
    prompt: "Explain the text in plain, simple language.",
    icon: BookOpen,
  },
  {
    id: "tone-friendly",
    label: "Write in friendly tone",
    category: "tone",
    prompt: "Rewrite the text in a friendly, approachable tone.",
    icon: MessageCircleHeart,
  },
  {
    id: "tone-casual",
    label: "Write in casual tone",
    category: "tone",
    prompt: "Rewrite the text in a casual conversational tone.",
    icon: MessageCircleMore,
  },
  {
    id: "tone-professional",
    label: "Write in professional tone",
    category: "tone",
    prompt: "Rewrite the text in a professional and polished tone.",
    icon: NotebookPen,
  },
  {
    id: "tone-excited",
    label: "Write in excited tone",
    category: "tone",
    prompt: "Rewrite the text in an excited and energetic tone.",
    icon: PartyPopper,
  },
  {
    id: "tone-confident",
    label: "Write in confident tone",
    category: "tone",
    prompt: "Rewrite the text in a confident and assured tone.",
    icon: Target,
  },
  {
    id: "tone-appreciative",
    label: "Write in appreciative tone",
    category: "tone",
    prompt: "Rewrite the text in an appreciative and grateful tone.",
    icon: ClipboardCheck,
  },
  {
    id: "tone-direct",
    label: "Write in direct tone",
    category: "tone",
    prompt: "Rewrite the text to be direct, concise, and unambiguous.",
    icon: PenLine,
  },
  {
    id: "tone-regretful",
    label: "Write in regretful tone",
    category: "tone",
    prompt: "Rewrite the text in a regretful and apologetic tone.",
    icon: RefreshCw,
  },
  {
    id: "tone-thoughtful",
    label: "Write in thoughtful tone",
    category: "tone",
    prompt: "Rewrite the text in a reflective and thoughtful tone.",
    icon: Sparkles,
  },
  {
    id: "tone-critical",
    label: "Write in a critical tone",
    category: "tone",
    prompt: "Rewrite the text in a critical and analytical tone.",
    icon: Scale,
  },
  {
    id: "tone-hopeful",
    label: "Write in a hopeful tone",
    category: "tone",
    prompt: "Rewrite the text in a hopeful and uplifting tone.",
    icon: TrendingUp,
  },
  {
    id: "tone-surprised",
    label: "Write in a surprised tone",
    category: "tone",
    prompt: "Rewrite the text in a tone that conveys surprise.",
    icon: PartyPopper,
  },
  {
    id: "tone-optimistic",
    label: "Write in an optimistic tone",
    category: "tone",
    prompt: "Rewrite the text in an optimistic, positive tone.",
    icon: Sparkles,
  },
  {
    id: "tone-curious",
    label: "Write in a curious tone",
    category: "tone",
    prompt: "Rewrite the text in an inquisitive and curious tone.",
    icon: BookOpen,
  },
  {
    id: "tone-assertive",
    label: "Write in an assertive tone",
    category: "tone",
    prompt: "Rewrite the text in an assertive and decisive tone.",
    icon: StretchHorizontal,
  },
  {
    id: "tone-informative",
    label: "Write in an informative tone",
    category: "tone",
    prompt: "Rewrite the text in an informative, neutral tone.",
    icon: CaseSensitive,
  },
  {
    id: "transform-bullets",
    label: "Turn into bullet list",
    category: "transform",
    prompt: "Transform the text into a clean bullet list.",
    icon: List,
  },
  {
    id: "transform-numbered",
    label: "Turn into numbered list",
    category: "transform",
    prompt: "Transform the text into a numbered list.",
    icon: ListOrdered,
  },
]

const actionLookup = new Map(actions.map((action) => [action.id, action]))

export function getActionById(actionId: string): Action | null {
  return actionLookup.get(actionId) ?? null
}